# Generated by Django 3.1.6 on 2021-08-05 02:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stock_ticker', models.CharField(max_length=6)),
                ('company_name', models.CharField(max_length=40)),
                ('number_stocks', models.PositiveIntegerField()),
                ('total_value', models.DecimalField(decimal_places=2, max_digits=12)),
            ],
        ),
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=30)),
                ('password', models.CharField(max_length=20)),
                ('balance', models.DecimalField(decimal_places=2, default=10000, max_digits=12)),
                ('account_value', models.DecimalField(decimal_places=2, default=10000, max_digits=12)),
                ('owned_stocks', models.ManyToManyField(blank=True, db_table='stock_table', to='userAccounts.Stock')),
            ],
        ),
    ]
