# Generated by Django 3.1.6 on 2021-06-04 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userAccounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='balance',
            field=models.DecimalField(decimal_places=2, default=10000.0, max_digits=9),
            preserve_default=False,
        ),
    ]
