# Generated by Django 3.1.6 on 2021-08-01 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userAccounts', '0002_account_balance'),
    ]

    operations = [
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stock_ticker', models.CharField(max_length=6)),
                ('company_name', models.CharField(max_length=40)),
                ('number_stocks', models.PositiveIntegerField()),
                ('total_value', models.DecimalField(decimal_places=2, max_digits=12)),
            ],
        ),
        migrations.AlterField(
            model_name='account',
            name='balance',
            field=models.DecimalField(decimal_places=2, max_digits=12),
        ),
        migrations.AddField(
            model_name='account',
            name='owned_stocks',
            field=models.ManyToManyField(to='userAccounts.Stock'),
        ),
    ]
