# Generated by Django 3.1.6 on 2021-08-02 02:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userAccounts', '0003_auto_20210801_2007'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='owned_stocks',
            field=models.ManyToManyField(blank=True, db_table='stock_table', to='userAccounts.Stock'),
        ),
    ]
