# Generated by Django 3.1.6 on 2021-08-04 23:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userAccounts', '0004_auto_20210802_0253'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='account_value',
            field=models.DecimalField(decimal_places=2, default=10000, max_digits=12),
        ),
    ]
