# Generated by Django 3.1.6 on 2021-08-05 01:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userAccounts', '0003_auto_20210805_0058'),
        ('userAccounts', '0005_account_account_value'),
    ]

    operations = [
    ]
